[grammars]

[grammars.tree-sitter-bash]
git     = "https://github.com/tree-sitter/tree-sitter-bash"
rev     = "f8fb3274f72a30896075585b32b0c54cad65c086"
path    = "./grammars/tree-sitter-bash"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-c]
git     = "https://github.com/tree-sitter/tree-sitter-c"
rev     = "7175a6dd5fc1cee660dce6fe23f6043d75af424a"
path    = "./grammars/tree-sitter-c"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-c-sharp]
git  = "https://github.com/tree-sitter/tree-sitter-c-sharp"
rev  = "5b60f99545fea00a33bbfae5be956f684c4c69e2"
path = "./grammars/tree-sitter-c-sharp"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-clojure]
git     = "https://github.com/sogaiu/tree-sitter-clojure"
rev     = "e57c569ae332ca365da623712ae1f50f84daeae2"
path    = "./grammars/tree-sitter-clojure"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-cmake]
git = "https://github.com/uyha/tree-sitter-cmake"
rev = "6e51463ef3052dd3b328322c22172eda093727ad"
path = "./grammars/tree-sitter-cmake"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-cpp]
git = "https://github.com/tree-sitter/tree-sitter-cpp"
path = "./grammars/tree-sitter-cpp"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-css]
git = "https://github.com/tree-sitter/tree-sitter-css"
rev = "769203d0f9abe1a9a691ac2b9fe4bb4397a73c51"
path = "./grammars/tree-sitter-css"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-d]
git = "https://github.com/gdamore/tree-sitter-d"
rev = "5566f8ce8fc24186fad06170bbb3c8d97c935d74"
path = "./grammars/tree-sitter-d"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-dockerfile]
git = "https://github.com/camdencheek/tree-sitter-dockerfile"
rev = "8ee3a0f7587b2bd8c45c8cb7d28bd414604aec62"
path = "./grammars/tree-sitter-dockerfile"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-elixir]
git = "https://github.com/elixir-lang/tree-sitter-elixir"
rev = "b20eaa75565243c50be5e35e253d8beb58f45d56"
path = "./grammars/tree-sitter-elixir"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-elm]
git = "https://github.com/elm-tooling/tree-sitter-elm"
rev = "df4cb639c01b76bc9ac9cc66788709a6da20002c"
path = "./grammars/tree-sitter-elm"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-erlang]
git = "https://github.com/the-mikedavis/tree-sitter-erlang"
rev = "9d4b36a76d5519e3dbf1ec4f4b61bb1a293f584c"
path = "./grammars/tree-sitter-erlang"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-glimmer]
git = "https://github.com/ember-tooling/tree-sitter-glimmer"
rev = "5dc6d1040e8ff8978ff3680e818d85447bbc10aa"
path = "./grammars/tree-sitter-glimmer"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-glsl]
git = "https://github.com/theHamsta/tree-sitter-glsl"
rev = "88408ffc5e27abcffced7010fc77396ae3636d7e"
path = "./grammars/tree-sitter-glsl"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-go]
git = "https://github.com/tree-sitter/tree-sitter-go"
rev = "64457ea6b73ef5422ed1687178d4545c3e91334a"
path = "./grammars/tree-sitter-go"
generate = true
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-hare]
git = "https://git.sr.ht/~ecmma/tree-sitter-hare"
rev = "2495958aaf3f93581c87ec020164255e80655331"
path = "./grammars/tree-sitter-hare"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-haskell]
git = "https://github.com/tree-sitter/tree-sitter-haskell"
rev = "d7ac98f49e3ed7e17541256fe3881a967d7ffdd3"
path = "./grammars/tree-sitter-haskell"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-hcl]
git = "https://github.com/MichaHoffmann/tree-sitter-hcl"
rev = "3cb7fc28247efbcb2973b97e71c78838ad98a583"
path = "./grammars/tree-sitter-hcl"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-html]
git = "https://github.com/tree-sitter/tree-sitter-html"
rev = "29f53d8f4f2335e61bf6418ab8958dac3282077a"
path = "./grammars/tree-sitter-html"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-java]
git = "https://github.com/tree-sitter/tree-sitter-java"
rev = "09d650def6cdf7f479f4b78f595e9ef5b58ce31e"
path = "./grammars/tree-sitter-java"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-javascript]
git = "https://github.com/tree-sitter/tree-sitter-javascript"
rev = "f772967f7b7bc7c28f845be2420a38472b16a8ee"
path = "./grammars/tree-sitter-javascript"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-json]
git = "https://github.com/tree-sitter/tree-sitter-json"
rev = "73076754005a460947cafe8e03a8cf5fa4fa2938"
path = "./grammars/tree-sitter-json"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-julia]
git = "https://github.com/tree-sitter/tree-sitter-julia"
rev = "8fb38abff74652c4faddbf04d2d5bbbc6b4bae25"
path = "./grammars/tree-sitter-julia"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-kotlin]
git = "https://github.com/fwcd/tree-sitter-kotlin"
rev = "a4f71eb9b8c9b19ded3e0e9470be4b1b77c2b569"
path = "./grammars/tree-sitter-kotlin"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-latex]
git = "https://github.com/latex-lsp/tree-sitter-latex"
rev = "8c75e93cd08ccb7ce1ccab22c1fbd6360e3bcea6"
path = "./grammars/tree-sitter-latex"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-lua]
git = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
rev = "88e446476a1e97a8724dff7a23e2d709855077f2"
path = "./grammars/tree-sitter-lua"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-markdown]
git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
rev = "62516e8c78380e3b51d5b55727995d2c511436d8"
path     = "./grammars/tree-sitter-markdown"
relative = "tree-sitter-markdown"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-markdown-inline]
git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
rev = "62516e8c78380e3b51d5b55727995d2c511436d8"
path     = "./grammars/tree-sitter-markdown"
relative = "tree-sitter-markdown-inline"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-nix]
git = "https://github.com/nix-community/tree-sitter-nix"
rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d"
path = "./grammars/tree-sitter-nix"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-ocaml]
git = "https://github.com/tree-sitter/tree-sitter-ocaml"
rev = "9965d208337d88bbf1a38ad0b0fe49e5f5ec9677"
path     = "./grammars/tree-sitter-ocaml"
relative = "ocaml"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-ocaml-interface]
git = "https://github.com/tree-sitter/tree-sitter-ocaml"
rev = "9965d208337d88bbf1a38ad0b0fe49e5f5ec9677"
path     = "./grammars/tree-sitter-ocaml"
relative = "interface"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-php]
git = "https://github.com/tree-sitter/tree-sitter-php"
rev = "f860e598194f4a71747f91789bf536b393ad4a56"
path = "./grammars/tree-sitter-php"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-prisma]
git = "https://github.com/victorhqc/tree-sitter-prisma"
rev = "eca2596a355b1a9952b4f80f8f9caed300a272b5"
path = "./grammars/tree-sitter-prisma"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-protobuf]
git = "https://github.com/yusdacra/tree-sitter-protobuf"
rev = "19c211a01434d9f03efff99f85e19f967591b175"
path = "./grammars/tree-sitter-protobuf"
generate = true
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-python]
git = "https://github.com/tree-sitter/tree-sitter-python"
rev = "4bfdd9033a2225cc95032ce77066b7aeca9e2efc"
path = "./grammars/tree-sitter-python"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-r]
git = "https://github.com/r-lib/tree-sitter-r"
rev = "cc04302e1bff76fa02e129f332f44636813b0c3c"
path = "./grammars/tree-sitter-r"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-ruby]
git = "https://github.com/tree-sitter/tree-sitter-ruby"
rev = "206c7077164372c596ffa8eaadb9435c28941364"
path = "./grammars/tree-sitter-ruby"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-rust]
git = "https://github.com/tree-sitter/tree-sitter-rust"
rev = "9c84af007b0f144954adb26b3f336495cbb320a7"
path = "./grammars/tree-sitter-rust"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-scheme]
git = "https://github.com/6cdh/tree-sitter-scheme"
rev = "af3af6c9356b936f8a515a1e449c32e804c2b1a8"
path = "./grammars/tree-sitter-scheme"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-scss]
git = "https://github.com/serenadeai/tree-sitter-scss"
rev = "c478c6868648eff49eb04a4df90d703dc45b312a"
path = "./grammars/tree-sitter-scss"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-sql]
git = "https://github.com/DerekStride/tree-sitter-sql"
rev = "da2d1eff425b146d3c8cab7be8dfa98b11d896dc"
path = "./grammars/tree-sitter-sql"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-svelte]
git = "https://github.com/Himujjal/tree-sitter-svelte"
rev = "be7f2e7db1fc19f0852265ec60923fc058380739"
path = "./grammars/tree-sitter-svelte"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-swift]
git = "https://github.com/alex-pinkus/tree-sitter-swift"
rev = "57c1c6d6ffa1c44b330182d41717e6fe37430704"
generate = true
path     = "./grammars/tree-sitter-swift"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-toml]
git = "https://github.com/ikatyang/tree-sitter-toml"
rev = "7cff70bbcbbc62001b465603ca1ea88edd668704"
path = "./grammars/tree-sitter-toml"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-typescript]
git = "https://github.com/tree-sitter/tree-sitter-typescript"
rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path     = "./grammars/tree-sitter-typescript"
relative = "typescript"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-tsx]
git = "https://github.com/tree-sitter/tree-sitter-typescript"
rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path     = "./grammars/tree-sitter-typescript"
relative = "tsx"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-vue]
git = "https://github.com/ikatyang/tree-sitter-vue"
rev = "91fe2754796cd8fba5f229505a23fa08f3546c06"
path = "./grammars/tree-sitter-vue"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-wgsl]
git = "https://github.com/szebniok/tree-sitter-wgsl"
rev = "272e89ef2aeac74178edb9db4a83c1ffef80a463"
path = "./grammars/tree-sitter-wgsl"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-xml]
git = "https://github.com/RenjiSann/tree-sitter-xml"
rev = "48a7c2b6fb9d515577e115e6788937e837815651"
path = "./grammars/tree-sitter-xml"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }

[grammars.tree-sitter-yaml]
git = "https://github.com/ikatyang/tree-sitter-yaml"
rev = "0e36bed171768908f331ff7dff9d956bae016efb"
path = "./grammars/tree-sitter-yaml"
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.cc", cpp = true, flags = [] }

[grammars.tree-sitter-zig]
git = "https://github.com/maxxnino/tree-sitter-zig"
rev = "0d08703e4c3f426ec61695d7617415fff97029bd"
path = "./grammars/tree-sitter-zig"
generate = true
parser  = { path = "parser.c", cpp = false, flags = [] }
scanner = { path = "scanner.c", cpp = false, flags = [] }
