name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: windows-latest
            artefact: windows-x86_64

          - runs-on: ubuntu-latest
            artefact: linux-x86_64

          - runs-on: macos-14
            artefact: macos-arm64

          - runs-on: macos-13
            artefact: macos-x86_64
    env:
      RELEASE_TAG_NAME: ${{ inputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl wget clang pkg-config
          sudo update-alternatives --set cc /usr/bin/clang

      - name: Install tree-sitter-cli
        run: |
          cargo install tree-sitter-cli@^0.22 --locked

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build grammars
        if: always()
        run: python ./make.py

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.artefact }}
          path: |
            output
          retention-days: 1
